### ISSUE TITLE
Flight height input

### ISSUE THREAD

**Issue by Geousman** [juanxo90/MAGCPD#1]
Dear Sirs,
I have issues with the flight height using both the first and second versions of this code. Initially I thought the issue had to do with emag data, however, I tried three different satellite magnetic data and I have the same issue. If you use flight height you get a negative depth to top. I have attached the three figures for the world digital magnetic anomaly map (wdmam), emag and LCS.
![wdmam](https://user-images.githubusercontent.com/52153988/121767785-29614580-cb8d-11eb-8eef-f6ae217f583e.jpg)

![emag](https://user-images.githubusercontent.com/52153988/121767801-46961400-cb8d-11eb-91e4-418a3f1acd3a.jpg)
![LCS](https://user-images.githubusercontent.com/52153988/121767816-57468a00-cb8d-11eb-9192-f2a0fbb5f4a5.jpg)

**Comment by juanxo90** [comment]
Dear Geousman
I think you may need to play with the wavenumber ranges, and also, try to reduce the fractal parameter, as I may consider you're using to high fractal parameters. Remember that the spectrum will have different slopes that are related with different layers. Please read:
https://www.sciencedirect.com/science/article/pii/S0921936698800042
http://dx.doi.org/10.1016/j.cageo.2016.02.015

As I mentioned before, probably this problem is related with the high use of fractal parameter, the adjust could not be the best, but you could have realistic results.

**Comment by Geousman** [comment]
Dear Sir,
Many thanks for the advise.
Cheers.
